[2024-02-26T14:07:30.648+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-16T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509
[2024-02-26T14:07:30.649+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-16T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-16T00:30:00+00:00/task_id=print_current_date_with_conetxt'
[2024-02-26T14:07:30.677+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-16T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509
[2024-02-26T14:07:30.678+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-16T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-16T00:30:00+00:00/task_id=print_current_date_with_conetxt'
[2024-02-26T14:07:30.856+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_dag_with_context.print_current_date_with_conetxt scheduled__2024-01-16T00:30:00+00:00 [queued]>
[2024-02-26T14:07:30.865+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_dag_with_context.print_current_date_with_conetxt scheduled__2024-01-16T00:30:00+00:00 [queued]>
[2024-02-26T14:07:30.866+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-02-26T14:07:30.881+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): print_current_date_with_conetxt> on 2024-01-16 00:30:00+00:00
[2024-02-26T14:07:30.888+0000] {standard_task_runner.py:57} INFO - Started process 618 to run task
[2024-02-26T14:07:30.890+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'python_dag_with_context', 'print_current_date_with_conetxt', 'scheduled__2024-01-16T00:30:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/03-python-operator-with-context.py', '--cfg-path', '/tmp/tmpplp609b6']
[2024-02-26T14:07:30.893+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask print_current_date_with_conetxt
[2024-02-26T14:07:30.931+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-16T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509
[2024-02-26T14:07:30.932+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-16T00:30:00+00:00/task_id=print_current_date_with_conetxt permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=python_dag_with_context/run_id=scheduled__2024-01-16T00:30:00+00:00/task_id=print_current_date_with_conetxt'
[2024-02-26T14:07:30.933+0000] {task_command.py:410} INFO - Running <TaskInstance: python_dag_with_context.print_current_date_with_conetxt scheduled__2024-01-16T00:30:00+00:00 [running]> on host 2fe49a870f57
[2024-02-26T14:07:31.019+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='heumsi' AIRFLOW_CTX_DAG_ID='python_dag_with_context' AIRFLOW_CTX_TASK_ID='print_current_date_with_conetxt' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T00:30:00+00:00'
[2024-02-26T14:07:31.020+0000] {logging_mixin.py:150} INFO - execution_date: 2024-01-16
[2024-02-26T14:07:31.021+0000] {logging_mixin.py:150} INFO - execution_date_nodash: 20240116
[2024-02-26T14:07:31.021+0000] {logging_mixin.py:150} INFO - 2024-01-16는 화요일입니다.
[2024-02-26T14:07:31.022+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-02-26T14:07:31.032+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=python_dag_with_context, task_id=print_current_date_with_conetxt, execution_date=20240116T003000, start_date=20240226T140730, end_date=20240226T140731
[2024-02-26T14:07:31.062+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-02-26T14:07:31.078+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
